# .streamlit/secrets.toml 파일 내용
KOREAINVEST_KEY = "PSSEoumxRJOMbiSgqLveyzfnaxLujHrgFxHO"
KOREAINVEST_SECRET = "1m/g1u3VbGiHhPcdkqzz24uuqSUfYlG5T90zHD/lhtPGoZecg+loKs0l8IvNDjs+JERQ6Rw4VON+B6p9a9eunFfwyqtZ2uM1Y0buVFJGMXDAVMO/++U09g0qxS+N9kul+ZDjktOek3EwrLY0RZGLL7w9iPeDzd4XTtaGYKIaXf8TQB6U3JU="
KOREAINVEST_ACC_NO = "63842572-01" # 네 계좌번호